import Head from 'next/head'
import Auth from '../components/Auth'
import Todo from './Todo'
import React  from 'react'
import useAuth from '../hooks/useAuth'
import { useRouter } from 'next/router'

export default function Home() {
  const{user,isLoggedIn}=useAuth()
  const router=useRouter()
  React.useEffect(() => {
    if (isLoggedIn){
  router.push('/Todo')
    }

  }, [user,isLoggedIn])
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
   <Auth/>

    </div>
  )
}
